CREATE TABLE [tblStates] (
  [ID] AUTOINCREMENT CONSTRAINT [ID] PRIMARY KEY UNIQUE NOT NULL,
  [StateFull] VARCHAR (255),
  [State] VARCHAR (255),
  [Field3] VARCHAR (255),
  [Field4] VARCHAR (255),
  [StateNum] LONG
)
